# Generated by Django 4.2.16 on 2024-12-12 15:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('name', models.CharField(help_text='Name of the bank type, e.g., Bkash, Rocket, Nagad', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('p2p', 'Peer-to-Peer'), ('p2c', 'Peer-to-Customer')], help_text='Category of the bank type', max_length=3)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Bank Type',
                'verbose_name_plural': 'Bank Types',
                'db_table': 'bank_type',
            },
        ),
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('bank_unique_id', models.CharField(help_text='Unique identifier for the bank', max_length=100, unique=True)),
                ('bank_name', models.CharField(help_text='Name of the bank', max_length=100)),
                ('account_number', models.CharField(help_text='Account number in the format +880XXXXXXXXX', max_length=15, validators=[django.core.validators.RegexValidator('^\\+880\\d{9,10}$', message='Account number must start with +880 and contain 9-10 digits')])),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=1.0, help_text='Minimum amount allowed', max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('maximum_amount', models.DecimalField(decimal_places=2, default=25000.0, help_text='Maximum amount allowed', max_digits=10, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(25000.0)])),
                ('daily_limit', models.DecimalField(decimal_places=2, default=0.0, help_text='Daily transaction limit', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('daily_usage', models.DecimalField(decimal_places=2, default=0.0, help_text='Daily usage so far', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly transaction limit', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('monthly_usage', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly usage so far', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('app_key', models.CharField(help_text='API key for the application', max_length=255)),
                ('secret_key', models.CharField(help_text='Secret key for the application', max_length=255)),
                ('agent', models.ForeignKey(help_text='Agent linked to the bank', on_delete=django.db.models.deletion.CASCADE, related_name='banks_agent', to='app_profile.profile')),
                ('bank_type', models.ForeignKey(help_text='Type of the bank', on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='app_bank.banktypemodel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'db_table': 'bank',
            },
        ),
    ]
