# Generated by Django 4.2.16 on 2024-12-08 01:44

import app_profile.models.profile
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('country', models.CharField(choices=[('US', 'United States'), ('IN', 'India'), ('UK', 'United Kingdom'), ('CA', 'Canada')], max_length=3, verbose_name='Country')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^(\\+88)?01[3-9]\\d{8}$', "Phone number must be a valid Bangladeshi number. Examples: '+8801855555555' or '01855555555'.")], verbose_name='Phone Number')),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Handle')),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('id_card', 'ID Card'), ('driver_license', 'Driver License')], max_length=20, verbose_name='Document Type')),
                ('front_side', models.FileField(upload_to=app_profile.models.profile.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Front Side')),
                ('back_side', models.FileField(blank=True, null=True, upload_to=app_profile.models.profile.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Back Side')),
                ('selfie_with_id', models.FileField(upload_to=app_profile.models.profile.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Selfie with ID/Passport')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
