# Generated by Django 4.2.16 on 2024-12-13 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0001_initial'),
        ('app_deposit', '0003_alter_deposit_agent_alter_deposit_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='app_profile.profile'),
            preserve_default=False,
        ),
    ]
